

services:
  backend:
    build: ./backend/restservices
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/jobs
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_MAIL_PASSWORD=${MAIL_PASS}
      - SPRING_MAIL_USERNAME=${MAIL_USER}
      - ZOOM_ACCOUNT_ID=${ZOOM_ACC}
      - ZOOM_CLIENT_SECRET=${ZOOM_SECRET}
      - ZOOM_CLIENT_ID=${ZOOM_ID}
    depends_on:
      - db

  frontend:
    build: ./frontend/my-app
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8080
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=jobs
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
